import type { Metadata } from 'next'
import { Space_Mono } from 'next/font/google'

import './globals.css'

const spaceMono = Space_Mono({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Currency Calculator App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spaceMono.className}>
        <main className='h-screen bg-emerald-100 flex justify-center items-center'>
          <div className='m-auto max-w-screen-md flex-1 h-full max-h-96 px-4'>
            <div className='rounded-3xl bg-white shadow-lg w-full p-8'>
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  )
}
